/* STAGING */

CREATE OR REPLACE TABLE yelp_business (
    business_id string,
    name string,
    address string,
    city string,
    state string,
    postal_code string,
    latitude string,
    longitude string,
    stars string,
    review_count string,
    is_open string,
    attributes string,
    categories string,
    hours string
);

CREATE OR REPLACE TABLE yelp_business (
    business_id string,
    name string,
    address string,
    city string,
    state string,
    postal_code string,
    latitude string,
    longitude string,
    stars string,
    review_count string,
    is_open string,
    attributes_NoiseLevel string,
    attributes_BikeParking string,
    attributes_RestaurantsAttire string,
    attributes_BusinessAcceptsCreditCards string,
    attributes_BusinessParking string,
    attributes_RestaurantsReservations string,
    attributes_GoodForKids string,
    attributes_RestaurantsTakeOut string,
    attributes_Caters string,
    attributes_WiFi string,
    attributes_RestaurantsDelivery string,
    attributes_HasTV string,
    attributes_RestaurantsPriceRange2 string,
    attributes_Alcohol string,
    attributes_Music string,
    attributes_BusinessAcceptsBitcoin string,
    attributes_GoodForDancing string,
    attributes_DogsAllowed string,
    attributes_BestNights string,
    attributes_RestaurantsGoodForGroups string,
    attributes_OutdoorSeating string,
    attributes_HappyHour string,
    attributes_RestaurantsTableService string,
    attributes_GoodForMeal string,
    attributes_WheelchairAccessible string,
    attributes_Ambience string,
    categories string,
    hours_Monday string,
    hours_Tuesday string,
    hours_Wednesday string,
    hours_Thursday string,
    hours_Friday string,
    hours_Saturday string,
    hours_Sunday string
);